### ISSUE TITLE
is there android version of this plugin

### ISSUE THREAD

**Issue by nelsonwilliam11** [Essent/nativescript-in-app-notifications#2]
the plugin is not supported for android

**Comment by dennis-montana** [comment]
We use this plugin to show push notifications when the app is running in the foreground. On Android these are displayed automatically, on iOS you need to show them yourself.  
That's why we didn't add support for Android.

If you need support for Android we're happy to accept a pull request. For example: have a look at our GcmListenerService in another project: https://github.com/Essent/nativescript-live-engage/blob/master/demo/app/my-gcm-listener-service.ts

**Comment by nelsonwilliam11** [comment]
hi there can you please make a demo about how to notify a user if someone liked their posts or commented or  someone started following them etc am building a social app with ng  been trying to do that but totally failed any sort of help is accepted
thanks

**Comment by dennis-montana** [comment]
When you receive a like or comment while the app is active you can just call:
```ts
InAppNotifications.getInstance().showNotification('Someone liked you', 'Like Received', () => {
    console.log('Tapped on like');
});
```
